'use strict';

// Usage: node scripts/evidence.js
//
// Stands the service up from the current checkout exactly as the README
// describes, records every command it runs (command, exit code, relevant
// output, verdict) and writes EVIDENCE.md. Nothing in the generated sections
// is typed by hand: a step that was not executed cannot appear as passed.
// WARNING: recreates the database named in DB_NAME.

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'EVIDENCE.md');
const NOTES = path.join(__dirname, 'evidence-notes.md');

const steps = [];

function run(title, command, { expectExit = 0, env = {}, relevant = out => out, why } = {}) {
  const started = Date.now();
  const r = spawnSync(command, { cwd: ROOT, shell: '/bin/sh', encoding: 'utf8', env: { ...process.env, ...env }, maxBuffer: 64 * 1024 * 1024 });
  const output = `${r.stdout || ''}${r.stderr || ''}`.trim();
  const exit = r.status === null ? `signal ${r.signal}` : r.status;
  const verdict = r.status === expectExit ? 'PASS' : 'FAIL';
  const envPrefix = Object.entries(env).map(([k, v]) => `${k}=${v} `).join('');
  steps.push({ title, command: `${envPrefix}${command}`, exit, expectExit, verdict, output, relevant: relevant(output), seconds: ((Date.now() - started) / 1000).toFixed(1), why });
  console.log(`${verdict.padEnd(5)} exit=${exit} (expected ${expectExit})  ${envPrefix}${command}`);
  return { ...r, output };
}

const tail = n => out => out.split('\n').slice(-n).join('\n');
const grep = re => out => out.split('\n').filter(l => re.test(l)).join('\n');

// ---------------------------------------------------------------- run
const node = run('Node.js version', 'node -v');
const npm = run('npm version', 'npm -v');
const osInfo = run('Operating system', process.platform === 'darwin'
  ? 'uname -srm && sw_vers'
  : 'uname -srm && (cat /etc/os-release 2>/dev/null | head -2)');
// EVIDENCE.md is this script's own output, so it is excluded from the check.
// A fingerprint of every tracked file except this script's own output: the same
// command on any checkout of the same source prints the same value, whatever
// the commit is called.
const FINGERPRINT = "git ls-files -s -- . ':!EVIDENCE.md' | git hash-object --stdin";
const rev = run('Source fingerprint (and whether tracked files differ from it)', `${FINGERPRINT} && git status --porcelain --untracked-files=no -- . ':!EVIDENCE.md'`);
run('Install dependencies from the lockfile', 'npm ci --no-audit --no-fund', { relevant: tail(3) });
run('Apply migrations to an empty database', 'npm run migrate -- --fresh', { relevant: grep(/\[migrate\]/) });
const dbv = run('Database server version', 'node scripts/db-version.js');
run('Load synthetic seed data', 'npm run seed', { relevant: grep(/\[seed\]|@/) });
run('Re-run migrations (must be a no-op)', 'npm run migrate', { relevant: grep(/\[migrate\]/) });
const verify = run('Verifier: every check', 'npm run verify', { relevant: grep(/^(Intake|node |database |\d+ passed|VERIFIED|NOT VERIFIED)/) });
// Keep this run's report: the negative run below writes its own.
let report = null;
try { report = JSON.parse(fs.readFileSync(path.join(ROOT, 'verify-report.json'), 'utf8')); } catch { /* verifier did not produce a report */ }
run('Verifier with the database unreachable must report NOT RUN and exit non-zero', 'node scripts/verify.js',
  { env: { DB_PORT: '1' }, expectExit: 1, relevant: grep(/ENV-DB|ENV-MARIADB|\d+ passed|VERIFIED/), why: 'demonstrates that a check that cannot run is never reported as passed' });
run('Audit chain verification (CLI) on the verified database', 'npm run audit:verify', { relevant: tail(5) });

// ---------------------------------------------------------------- write
// Leave verify-report.json as the report of the real run, not the negative one.
if (report) fs.writeFileSync(path.join(ROOT, 'verify-report.json'), `${JSON.stringify(report, null, 2)}\n`);

const md = [];
const fence = s => `\`\`\`\n${s || '(no output)'}\n\`\`\``;
md.push('# EVIDENCE');
md.push('');
md.push(`Generated by \`node scripts/evidence.js\` at ${new Date().toISOString()}. This file is regenerated, not hand-edited: every command below was executed by that script and its exit code and output are recorded as they occurred. Sections under "Notes" at the end are written by hand and say so.`);
md.push('');
md.push('## Runtime the evidence was produced on');
md.push('');
md.push('| Item | Value | Command |');
md.push('|---|---|---|');
md.push(`| Node.js | \`${node.output}\` | \`node -v\` |`);
md.push(`| npm | \`${npm.output}\` | \`npm -v\` |`);
md.push(`| Database server | \`${dbv.output}\` | \`node scripts/db-version.js\` (\`SELECT VERSION(), @@version_comment\`) |`);
md.push(`| OS (host running Node.js) | \`${osInfo.output.split('\n').join(' · ')}\` | see step 3 |`);
md.push(`| CPU architecture | \`${os.arch()}\` | \`process.arch\` |`);
const [sha, ...dirty] = rev.output.split('\n').filter(Boolean);
md.push(`| Source fingerprint | \`${sha || 'unknown'}\`${dirty.length ? ` (**modified: ${dirty.map(d => d.trim()).join(', ')}**)` : ' (tracked files unmodified)'} | \`${FINGERPRINT.replace(/\|/g, '\\|')}\` |`);
md.push('');
const overall = steps.every(s => s.verdict === 'PASS') && report && report.verified;
md.push(`**Overall: ${overall ? 'VERIFIED' : 'NOT VERIFIED'}**: ${steps.filter(s => s.verdict === 'PASS').length}/${steps.length} commands behaved as expected; verifier ${report ? `${report.counts.PASS} passed, ${report.counts.FAIL} failed, ${report.counts['NOT RUN']} not run` : 'produced no report'}.`);
md.push('');
md.push('## Commands executed');
md.push('');
steps.forEach((s, i) => {
  md.push(`### ${i + 1}. ${s.title}: ${s.verdict}`);
  md.push('');
  md.push(`- Command: \`${s.command}\``);
  md.push(`- Exit code: \`${s.exit}\` (expected \`${s.expectExit}\`) · ${s.seconds}s`);
  if (s.why) md.push(`- Purpose: ${s.why}`);
  md.push('');
  md.push(fence(s.relevant));
  md.push('');
});

md.push('## Requirement-by-requirement results');
md.push('');
if (!report) {
  md.push('The verifier did not write verify-report.json. **Every requirement below is unverified.**');
} else {
  md.push(`Source: \`npm run verify\` (step ${steps.indexOf(steps.find(s => s.command === 'npm run verify')) + 1}, exit code \`${verify.status}\`). To re-run a single check: \`node --test --test-concurrency=1 --test-name-pattern="^\\[ID\\]" test/*.test.js\`.`);
  md.push('');
  const { GROUPS } = require('./lib/checks');
  let group;
  for (const c of report.checks) {
    if (c.group !== group) {
      group = c.group;
      md.push(`### ${GROUPS[group]}`);
      md.push('');
      md.push('| Check | Requirement | Verdict | Evidence |');
      md.push('|---|---|---|---|');
    }
    const tests = (c.tests || []).map(t => `${t.result} ${t.name.replace(/^\[[^\]]+\]\s*/, '')}${t.duration_ms !== null && t.duration_ms !== undefined ? ` (${t.duration_ms} ms)` : ''}${t.error ? `: ${t.error}` : ''}`);
    const evidence = (tests.length ? tests : [c.detail || '']).map(x => x.replace(/\|/g, '\\|')).join('<br>');
    md.push(`| ${c.id} | ${c.title.replace(/\|/g, '\\|')} | **${c.status}** | ${evidence} |`);
    const next = report.checks[report.checks.indexOf(c) + 1];
    if (!next || next.group !== group) md.push('');
  }
  if (report.other_failures.length) {
    md.push('### Other failures');
    md.push('');
    for (const f of report.other_failures) md.push(`- FAIL ${f}`);
    md.push('');
  }
}

md.push('<details><summary>Full verifier output (step "Verifier: every check")</summary>');
md.push('');
md.push(fence(verify.output));
md.push('');
md.push('</details>');
md.push('');
if (fs.existsSync(NOTES)) md.push(fs.readFileSync(NOTES, 'utf8').trim(), '');

fs.writeFileSync(OUT, `${md.join('\n')}\n`);
console.log(`\nwrote ${path.relative(process.cwd(), OUT)}: ${overall ? 'VERIFIED' : 'NOT VERIFIED'}`);
process.exit(overall ? 0 : 1);
